// examples/react-vite/src/ContinentList.jsx
import * as React from 'react';
import { UISref, UISrefActive, UIView } from '@uirouter/react';

export class ContinentList extends React.Component {
  render() {
    const { continents } = this.props;
    return (
      <div>
        <h3>Continents</h3>

        {continents.map((continent) => {
          return (
            <UISrefActive class="active" key={continent}>
              <span style={{ margin: '1em' }}>
                <UISref to=".countrylist" params={{ continent }}>
                  <a>{continent}</a>
                </UISref>
              </span>
            </UISrefActive>
          );
        })}

        <UIView />
      </div>
    );
  }
}

// examples/angular-cli/src/app/continentList.component.ts
import { Input, Component } from '@angular/core';

@Component({
  selector: 'continent-list-cmp',
  template: `
    <h3>Continents</h3>

    <span *ngFor="let continent of continents" style="margin: 1em" uiSrefActive="active">
      <a uiSref=".countrylist" [uiParams]="{ continent: continent }">{{ continent }}</a>
    </span>

    <ui-view></ui-view>
  `,
})
export class ContinentListComponent {
  @Input() continents: string[] = [];
}
