// examples/angular-cli/src/app/countryDetail.component.ts
import { Input, Component } from '@angular/core';

@Component({
  selector: 'country-detail-cmp',
  template: `
    <h3>{{ country }}</h3>
    <div style="height: 100px;">
      <img [src]="imageSrc()" [alt]="'flag of ' + country">
    </div>
  `,
})
export class CountryDetailComponent {
    @Input() country: string;

    imageSrc() {
      if (!this.country) { return ''; }
      const prefix = 'http://www.randomlists.com/img/national-flags/';
      const imageName = this.country.toLowerCase().replace(/ /g, '_');
      return `${prefix}${imageName}.gif`;
    }
}

// examples/react-vite/src/CountryDetail.jsx
import * as React from 'react';

export class CountryDetail extends React.Component {
  render() {
    const { country } = this.props;
    if (!country) return null;

    const prefix = '//www.randomlists.com/img/national-flags/';
    const imageName = country.toLowerCase().replace(/ /g, '_');
    const imgSrc = `${prefix}${imageName}.gif`;
    const alt = `flag of ${country}}`;

    return (
      <div>
        <h3>{country}</h3>
        <div style={{ height: '100px' }}>
          <img src={imgSrc} alt={alt} />
        </div>
      </div>
    );
  }
}
